services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: dev
    container_name: zastepstwa_backend_dev
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - CI=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/backend/api/node_modules
      - /app/frontend/node_modules

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: dev
    container_name: zastepstwa_frontend_dev
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.development
    environment:
      - CI=true
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules
      - /app/backend/api/node_modules
      - /app/frontend/node_modules
