packages:
  - "frontend"
  - "backend/api"
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
overrides:
  "typescript-eslint>typescript": "npm:@typescript/typescript6@^6.0.0"
  "@typescript-eslint/typescript-estree>typescript": "npm:@typescript/typescript6@^6.0.0"
  "@typescript-eslint/parser>typescript": "npm:@typescript/typescript6@^6.0.0"
