[project]
name = "zastepstwa-zsk"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "lxml>=6.1.1",
    "python-dotenv>=1.2.2",
]
[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
]

[tool.ruff]
line-length = 152
target-version = "py314"

[tool.ruff.lint]
extend-select = [
    "W",
    "I",
    "B",
    "UP",
    "FURB",
    "E",
    "COM",
    "C4",
    "N",
    "SIM",
]
ignore = [
    "COM812"
]
